// apps/web/src/lib/ScrollText.svelte
<script lang="ts">
  interface Props {
    text?: string;
    color?: string;
    class?: string;
    /** Inline style string applied to the outer container. */
    style?: string;
    speedPxPerSec?: number;
    minWidthToScroll?: number;
    gapPx?: number;
  }

  let {
    text = "",
    color,
    class: className = "",
    style = "",
    speedPxPerSec = 24,
    minWidthToScroll,
    gapPx = 32,
  }: Props = $props();

  let outer = $state<HTMLDivElement | null>(null);
  let item = $state<HTMLSpanElement | null>(null);

  let animate = $state(false);
  let duration = $state(10);
  let scrollDistance = $state(0);
  let isRightAligned = $state(false);

  function measure() {
    if (!outer || !item) return;

    const parent = outer.parentElement;
    isRightAligned = parent ? window.getComputedStyle(parent).textAlign === "right" : false;

    const widthConstraint = typeof minWidthToScroll === "number" ? outer.clientWidth <= minWidthToScroll : false;
    const contentWidth = item.scrollWidth;
    const outerWidth = outer.clientWidth;
    const overflow = !!text && (widthConstraint || contentWidth > outerWidth + 2);

    if (overflow) {
      const distance = contentWidth + gapPx;
      const safeSpeed = Math.max(0.1, Math.abs(speedPxPerSec || 0));
      scrollDistance = distance;
      duration = Math.max(0.5, distance / safeSpeed);
      animate = true;
    } else {
      animate = false;
      scrollDistance = 0;
    }
  }

  $effect(() => {
    // Re-run when any measurement input changes.
    void text;
    void speedPxPerSec;
    void minWidthToScroll;
    void gapPx;
    if (!outer || !item) return;

    const initial = window.setTimeout(measure, 50);
    const ro = new ResizeObserver(() => window.requestAnimationFrame(measure));
    ro.observe(outer);
    ro.observe(item);
    const onResize = () => window.requestAnimationFrame(measure);
    window.addEventListener("resize", onResize);
    document.fonts?.ready.then(measure).catch(() => {});

    return () => {
      clearTimeout(initial);
      ro.disconnect();
      window.removeEventListener("resize", onResize);
    };
  });

  const animationName = $derived(isRightAligned ? "marquee-scroll-right" : "marquee-scroll-left");
  const wrapperStyle = $derived(
    [
      "display:inline-flex",
      animate ? `gap:${gapPx}px` : "",
      animate ? `animation:${animationName} ${duration.toFixed(2)}s linear infinite` : "",
      animate ? "will-change:transform" : "",
      `--scroll-distance:${scrollDistance}px`,
    ]
      .filter(Boolean)
      .join(";"),
  );
</script>

<div bind:this={outer} class="marquee {animate ? 'marquee--animate' : ''} {className}" style="min-width:0;position:relative;{style}">
  <div class="marquee__wrapper" style={wrapperStyle}>
    <span bind:this={item} class="marquee__item" style="color:{color};white-space:nowrap;display:inline-block">{text}</span>
    <span class="marquee__item" aria-hidden="true" style="color:{color};white-space:nowrap;display:{animate ? 'inline-block' : 'none'}">{text}</span>
  </div>
</div>

// src/components/ScrollText.tsx
// src/components/ScrollText.tsx
import React, { useEffect, useRef, useState } from "react";

type Props = {
  text?: string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  speedPxPerSec?: number; // scrolling speed in pixels per second
  minWidthToScroll?: number; // trigger scrolling when outer width <= this
  gapPx?: number; // gap between repeated labels
};

export default function ScrollText({ 
  text = "", 
  color, 
  className = "", 
  style, 
  speedPxPerSec = 24, 
  minWidthToScroll, 
  gapPx = 32
}: Props) {
  const outerRef = useRef<HTMLDivElement | null>(null);
  const itemRef = useRef<HTMLSpanElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const [animate, setAnimate] = useState(false);
  const [duration, setDuration] = useState(10);
  const [scrollDistance, setScrollDistance] = useState(0);
  const [isRightAligned, setIsRightAligned] = useState(false);

  useEffect(() => {
    const outer = outerRef.current;
    const item = itemRef.current;
    if (!outer || !item) return;

    const measure = () => {
      const currentOuter = outerRef.current;
      const currentItem = itemRef.current;
      if (!currentOuter || !currentItem) return;

      // Detect alignment from parent context
      const parent = currentOuter.parentElement;
      if (parent) {
        const computedStyle = window.getComputedStyle(parent);
        setIsRightAligned(computedStyle.textAlign === "right");
      } else {
        setIsRightAligned(false);
      }

      const widthConstraint = typeof minWidthToScroll === "number"
        ? currentOuter.clientWidth <= minWidthToScroll
        : false;
      const contentWidth = currentItem.scrollWidth;
      const outerWidth = currentOuter.clientWidth;
      const overflow = !!text && (widthConstraint || contentWidth > outerWidth + 2);

      if (overflow) {
        const distance = contentWidth + gapPx;
        const safeSpeed = Math.max(0.1, Math.abs(speedPxPerSec || 0));
        const calcDuration = distance / safeSpeed;
        setScrollDistance(distance);
        setDuration(Math.max(0.5, calcDuration));
        setAnimate(true);
      } else {
        setAnimate(false);
        setScrollDistance(0);
      }
    };

    // Initial measure with delay to ensure DOM is ready
    const initialTimeout = window.setTimeout(measure, 50);
    
    // Measure on changes
    const ro = new ResizeObserver(() => {
      window.requestAnimationFrame(measure);
    });
    ro.observe(outer);
    ro.observe(item);

    const onResize = () => {
      window.requestAnimationFrame(measure);
    };
    window.addEventListener("resize", onResize);
    
    // Re-measure when fonts load
    if (document.fonts) {
      document.fonts.ready.then(measure);
    }
    
    return () => {
      clearTimeout(initialTimeout);
      window.removeEventListener("resize", onResize);
      ro.disconnect();
    };
  }, [text, speedPxPerSec, minWidthToScroll, gapPx]);

  const containerStyle: React.CSSProperties = {
    minWidth: 0,
    position: "relative",
    ...(style || {}),
  };

  // Choose animation direction based on alignment
  const animationName = isRightAligned ? "marquee-scroll-right" : "marquee-scroll-left";

  const wrapperStyle: React.CSSProperties = {
    display: "inline-flex",
    gap: animate ? `${gapPx}px` : undefined,
    animation: animate ? `${animationName} ${duration.toFixed(2)}s linear infinite` : undefined,
    willChange: animate ? "transform" : undefined,
    ["--scroll-distance" as string]: `${scrollDistance}px`,
  };

  return (
    <div 
      ref={outerRef} 
      className={`marquee ${animate ? "marquee--animate" : ""} ${className}`} 
      style={containerStyle}
    >
      <div ref={wrapperRef} className="marquee__wrapper" style={wrapperStyle}>
        <span
          ref={itemRef}
          className="marquee__item"
          style={{ color, whiteSpace: "nowrap", display: "inline-block" }}
        >
          {text}
        </span>
        <span
          className="marquee__item"
          aria-hidden="true"
          style={{
            color,
            whiteSpace: "nowrap",
            display: animate ? "inline-block" : "none",
          }}
        >
          {text}
        </span>
      </div>
    </div>
  );
}
